version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"  # Django app
      - "5678:5678"  # Debugger port
    volumes:
      - .:/app  # Mount local project directory to container
    #command: python manage.py runserver 0.0.0.0:8000
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
